export const NAV_MENU = [
  { title: 'Portfolio', icon: '', route: '/portfolio' },
  { title: 'Fundamental', icon: '', route: '/fundamental' },
  { title: 'Template Driven Forms', icon: '', route: '/template-driven-form' },
  { title: 'Cart Calculation', icon: '', route: '/cart-calculation' },
  { title: 'Directives', icon: '', route: '/directives' },
  { title: 'Grouping Elements', icon: '', route: '/grouping-elements' },
  { title: 'Lifecycle', icon: '', route: '/lifecycle' },
  { title: 'Decorator', icon: '', route: '/decorator' },
  { title: 'Input Decorator', icon: '', route: '/input-decorator' },
  { title: 'Output Decorator', icon: '', route: '/output-decorator' },
  { title: 'Input & Output', icon: '', route: '/input-output-decorator' },
  { title: '@ViewChild', icon: '', route: '/view-child' },
  { title: '@ContainChild', icon: '', route: '/contain-child' },
  { title: 'To Do List', icon: '', route: '/todo' },
  { title: 'Dashboard', icon: '', route: '/dashboard' },
  { title: 'Users', icon: '', route: '/users' },
];
